# Generated by Django 4.2.9 on 2024-10-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artwork", "0002_post_thumbnail_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="post_qr_codes/"),
        ),
    ]
