# Generated by Django 4.2.9 on 2024-10-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_post_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
